### ISSUE TITLE
Bug in flood detection

### ISSUE THREAD

**Issue by wfjsw** [SEEDTEAM/TeleSeed#111]
Well, one day a people get in my group with flood lock enabled. He post a large amount of **pics** & he did not get kicked. But another one sent 5 **text** msg at a time and got kicked then. Is there a bug in flood detection algorithm?

**Comment by Imandaneshi** [comment]
I don't think so 
Maybe your servers network had a problem ? or your redis DB

**Comment by wfjsw** [comment]
Nope. After the text one got kicked, the pic one continued to flood after one of my mods came up and kick by command. So I don't think there is problem in network & db

**Comment by Imandaneshi** [comment]
There is no bugs in flood detection algorithm as far as i know 
Maybe he was mod or owner ?

**Comment by wfjsw** [comment]
No and Never.
If he is mod & owner my mod can't kick him.

**Comment by TiagoDanin** [comment]
The group and normal or supergroup?

**Comment by wfjsw** [comment]
@TiagoDanin normal, with TeleSeed v2

BTW Seed v4 cannot add&rem normal group

**Comment by TiagoDanin** [comment]
Sorry for the delay

There is no error.
The v2 does not detect amount of message,
but the time between messages, the default is two second.
- Recommend uses the TeleSeed V4 (improved the anti-spam)

**Comment by wfjsw** [comment]
OK. Closing it...

BTW Seed v4 don't work in supergroup over 200 members.
