### ISSUE TITLE
attempt to index field '?' (a nil value)

### ISSUE THREAD

**Issue by EdEn922** [SEEDTEAM/TeleSeed#113]
Today I'm keep getting this error while using commands such as /link /owner etc. whereas everything was working perfectly last night! Does anyone know what the problem is? 
solved

**Comment by DioneB** [comment]
why you solved ?

**Comment by EdEn922** [comment]
I'm not certain how that happened! I followed the tutorials on telegram
geeks. However the problem got solved after calling /add command on super
groups! Still, I'm not quite sure 'that' really fixed the problem or not!

**Comment by DioneB** [comment]
ohhh yeah, I had forgotten, thanks man
