### ISSUE TITLE
[v4] Doesn't respond suddenly in only one supergroup 

### ISSUE THREAD

**Issue by xeniun** [SEEDTEAM/TeleSeed#122]
From yesterday bot had stopped to respond in only one of my supergroups
I had tried to update repository and restart bot and server services. 
I had tried to simulate a fresh install but nothing comes right. 
This group have about one thousand of user. 
Nothing in my log except for one irripetibile error on line 473 of .///bot/utils.lua: bad argument #1 to 'len' (string expected, got boolean).

**Comment by TiagoDanin** [comment]
FIX: [c383cc2](https://github.com/SEEDTEAM/TeleSeed/commit/c383cc24e6865112043292bb0e23bd12ae50dc10)

Open Terminal:
- 1. `./launch update`
- 2. `./launch`

**Comment by xeniun** [comment]
Ok, I think it's fixed. We can close that. Thank you =)
