### ISSUE TITLE
Problems with bot in stats / photo / mute

### ISSUE THREAD

**Issue by alexandrecg89** [SEEDTEAM/TeleSeed#125]
hello, I am having problem in stats.lua in Supergroup .. when I give the command he does not show number of users and messages nor dels name is empty .. already in the group will be normal what could this be ???
else piece of photo bot .. give the command tells me to put the photo put talks on altered photo but does not change the picture of the bot v1 worked usual .. q ue can this be ??
and the last mute command in no case give the command works but he says that this muted but the person normal or send photos and videos regular talks,, what could be ???

I'm sorry but I'm using the language translator

**Comment by TiagoDanin** [comment]
- `/stats` Normal
- Commands: `/mute [type]`, `/setphoto`, `/muteuser`and others, not run correctly :/ (Note: only in group)

This will be resolved soon, thank :D

**Comment by TiagoDanin** [comment]
Commit: [FIX #125](https://github.com/SEEDTEAM/TeleSeed/commit/38e84b651c4df27076952207de2470f53b0bd3a9) 43f0614
Check now :D

Open Terminal:
- 1. `./launch update`
- 2. `./launch`

Open Telegram
- 1. Open bot on group
- 2. `/add`

**Comment by F3ociety** [comment]
tnx buddy its working :D

**Comment by TiagoDanin** [comment]
Closed.
- Confirmation of solved by a user
- Inactive
