### ISSUE TITLE
Is not working in big supergroups

### ISSUE THREAD

**Issue by ticoti** [SEEDTEAM/TeleSeed#139]
Since a week or two telegram-cli is not receiving messages from the big supergroups so the bot is not working in that supergroups :/

**Comment by ghost** [comment]
Nice

**Comment by DioneB** [comment]
the bot not working in groups wich 500+ members

**Comment by wfjsw** [comment]
the bot not working in groups with 200+ members

**Comment by TiagoDanin** [comment]
I found a way for work: 
- Open Telegram Desktop (Not Web or android...)
- Run bot
- On terminal paste: `channel_list`

**Comment by wfjsw** [comment]
@TiagoDanin The hack works for ... less than 30s

alright it does work by launch a telegram desktop and **keep it opened a supergroup at foreground**

**Comment by kamikazechaser** [comment]
I have noticed that it works for some people. I tried very hard to get it working and used over 5 teleseed clones but it didn't work. However some guy got his bot working (A teleseed clone i dont know of) instantly. The group has 230+ members.

**Comment by wfjsw** [comment]
In order to get the bot working, one should chat actively on a bot account to activate it so that it could receive push notifications from supergroups. That operation takes around a week (or more).

**Comment by itum** [comment]
bot is not working on big supergroups why we can not solve it? 
i change my number to kuwait / egypt phone num nothing changed...

**Comment by kamikazechaser** [comment]
The solution by @wfjsw is correct. You will have to wait.

**Comment by Imandaneshi** [comment]
bot works in big supergroups when you mention it,
like `/res @your_bot_username`
you can get commands working by adding @your_bot_username at first/end of them like
`@teleseed /id`

**Comment by Imandaneshi** [comment]
Also this limit doesn't apply on bots with philippine numbers, they get all messages, i saw a TeleSeed clone working on a supergroup with 5K members

**Comment by itum** [comment]
i hvaev an egypht & kuwatian number still no working on big supergroups more than 300 members...!
also all of operators in Iran is not working(irancell,MCI,Rightel)
are you sure if i use philipines numbers i can do it ? where i can find it??

**Comment by Imandaneshi** [comment]
Well, There was an app "Talk2", But it died so , for now there is no way

**Comment by itum** [comment]
bot works in big supergroups when you mention it,
like /res @your_bot_username
you can get commands working by adding @your_bot_username at first/end of them like

## @teleseed /id

It does not working for me...I tested not worked also to my test supergroup with 2 usrs.

**Comment by itum** [comment]
## Well, There was an app "Talk2", But it died so , for now there is no way

well i was used beforem,no code telegram will send to you.
seems that telegram block all of virtual numbers..

**Comment by Imandaneshi** [comment]
Of course it doesn't work, you should modify your code 
But `/res @your_bot_username` Should work and be sure you are getting notifications from that group

**Comment by itum** [comment]
In order to get the bot working, one should chat actively on a bot account to activate it so that it could receive push notifications from supergroups. That operation takes around a week (or more).

---

i dnt understand this method,i think this is not always online...any solve?

**Comment by itum** [comment]
Of course it doesn't work, you should modify your code 

## But /res @your_bot_username Should work and be sure you are getting notifications from that group

where is the code that i should to modify that? 
if i modify that code can i add our bot to big supergroups??

**Comment by Imandaneshi** [comment]
No it won't work untill it's mentioned, even if you modify your code still it's pointless since it's not getting all of the messages , i mean mute,settings doesn't work

**Comment by itum** [comment]
@Imandaneshi if u use @mybot /add is not working sorry:(
what is the solve ? change my number?

**Comment by Imandaneshi** [comment]
For now, yes, you should change your number ,  we are using a real german number for TeleSeed and even that doesn't work

**Comment by wfjsw** [comment]
@kamikazechaser Not only wait but use it actively, like a real person.

**Comment by itum** [comment]
@Imandaneshi I changed my number to France number and still is not working on 500 members!
just when i online with my bot device i can add it to big group and when i dnt online that device it is not working more...!

**Comment by Dragon-Born** [comment]
Wait for new version
