### ISSUE TITLE
problem whith  bot

### ISSUE THREAD

**Issue by ghost** [SEEDTEAM/TeleSeed#140]
I installed on my server  i added my robot in the Super Group does not work but is not actively Please consider as soon as possible And build the robot, but the message was  chat not found  ???

**Comment by TiagoDanin** [comment]
Could rephrase the question?

**Comment by TiagoDanin** [comment]
@arbab878 this #139 ?

**Comment by microsoftTG** [comment]
@Tiagodanin how fix this issue

**Comment by DioneB** [comment]
@Tiagodanin how fix this issue ?

**Comment by TiagoDanin** [comment]
I don't know what is the problem

**Comment by TiagoDanin** [comment]
Closed: 
- Inactive
- No answer
