### ISSUE TITLE
BLOCK IS DONT WORK

### ISSUE THREAD

**Issue by dr-peterson** [SEEDTEAM/TeleSeed#143]
why block user is dont work??

**Comment by TiagoDanin** [comment]
Fix in soon

**Comment by TiagoDanin** [comment]
Commit: [Update banlist and fix #143](https://github.com/SEEDTEAM/TeleSeed/commit/3aae4a79222ffe40f496b0b10a5009af554a52bc) 0f3d52b

Open Terminal:
- 1. `./launch update`
- 2. `./launch`

**Comment by mahdib9** [comment]
سلام

**Comment by amirkingred** [comment]
Hi.kick and ban is not work.please fix.●︿●

**Comment by ghost** [comment]
please help me about error exiting in seed super groups

**Comment by TiagoDanin** [comment]
@amirkingred Use the `/add`
![image](https://cloud.githubusercontent.com/assets/5731176/14464816/e38d7116-00a6-11e6-821b-34a31ee277b4.png)

@navidka Please create a [new issues](https://github.com/SEEDTEAM/TeleSeed/issues/new)

**Comment by TiagoDanin** [comment]
Closed.
- Inactive
