### ISSUE TITLE
Is not working in open supergroups

### ISSUE THREAD

**Issue by toaskoas** [SEEDTEAM/TeleSeed#144]
# bot on is not working

**Comment by TiagoDanin** [comment]
Please explain your problem....
The what exactly doesn't work?

**Comment by microsoftTG** [comment]
Bot not detect messeges in 200+ member super groups but works in 200- super groups 
Pls help me fast

**Comment by F3ociety** [comment]
@MicrosoftTg That's not TeleSeed fault it's about the Tg

**Comment by microsoftTG** [comment]
@Amir-screen i will update tg but thats not changed  i clone teleseed twice but bot not detect any messege in +200 member groups

**Comment by TiagoDanin** [comment]
Duplicate: #139
