### ISSUE TITLE
bot has been crashed.{scheme.tl}

### ISSUE THREAD

**Issue by ghost** [SEEDTEAM/TeleSeed#163]
to this update [scheme.t](https://github.com/Rondoozle/tgl/blob/f3079900a8bdf3fc03fd24945a9473b1903ba81f/scheme.tl) bot has been fast crash. fix it

**Comment by TiagoDanin** [comment]
This the error?
![image](https://cloud.githubusercontent.com/assets/5731176/14708293/3faab952-07ca-11e6-87cb-2e15f62de61d.png)

**Comment by BH-YAGHI** [comment]
no bot is fast freez.
 *** 1461244053.003609 lua: attempt to call a boolean value                                                                                                
> SIGNAL received                                                                                                                                          
h

**Comment by ghost** [comment]
NO, I dont see that error this update problem is For Freez Bot is fast freez.❄️

``` bash
 *** 1461244053.003609 lua: attempt to call a boolean value                                                                                                
> SIGNAL received                                                                                                                                          
h 
```

and any time bot recive double-linked freez

``` bash
*** Error in `./tg/bin/telegram-cli': corrupted double-linked list: 0x000000000de028f0 ***
SIGNAL received 
```

![image](https://cloud.githubusercontent.com/assets/17055732/14710916/98846db2-07ec-11e6-9a37-6cae794ef7bd.png)

(Tiago > EDIT: No bold pls...)

**Comment by TiagoDanin** [comment]
Pls..., error log together with the last message received

**Comment by ghost** [comment]
I don't can't give you because I don't know how time bot receive this crash. 
But  I thinking Bot  receive This crash when member send fast link to GP and bot can't remove fast link so crashed ! 

To this update bot very fast crashing I don't know why but if you know so fix it !

**Comment by Imandaneshi** [comment]
It hapens when tg tries to do more than 2 commands simultaneously in a chat, for now there is no way to fix it, u can use [kill.sh](https://gist.github.com/Imandaneshi/3e76dfdc6e1e9745d98f075283f1ae24)
which kills bot every 2000 seconds
