### ISSUE TITLE
muteuser [bug]

### ISSUE THREAD

**Issue by ghost** [SEEDTEAM/TeleSeed#164]
# muteuser with reply and username for Modod is dont worked.

 *_Modod must be mute with ID *_

its better owner and promote can mute user by reply or @username

**Comment by F3ociety** [comment]
@BH-YAGHI 
Man just check the `supergroup.lua` and read it before opening an issues reading will help you to don`t waste someone time ...

![screenshot_20160422204128](https://cloud.githubusercontent.com/assets/16509569/14747732/13a2e42c-08cb-11e6-9969-43ac1f3b5a10.png)

**Comment by TiagoDanin** [comment]
Check the update
Open Terminal:
- 1. `./launch update`

If the Group and added
Open Group:
- 1. `/add`

**Comment by ghost** [comment]
@TiagoDanin  دراز بی مصرف این کوسه شعر چیه نوشتی عوض اینکه فایلو درست کنی

**Comment by ghost** [comment]
@TiagoDanin  i say you OWNER or MOMOD cant mute by replay, what is this say me!!?

**Comment by F3ociety** [comment]
@BH-YAGHI Man plz stop insulting i gave you the solution .... Just check it  and it should works fine

**Comment by ghost** [comment]
بابا کوسع شعر نوشتی امیر ،اونی که دادی سروته نداره خودم فردا درستش میکنم میذارم تو دهن این دراز بی مصرف 
@Amir-screen

**Comment by Imandaneshi** [comment]
@BH-YAGHI There is no problem , you are just wasting your time by opening random issues. Also stop the persian

**Comment by ghost** [comment]
Mute by replay for owner don't work if you think it is worked test it before close 😒
