### ISSUE TITLE
[URGENT][BIG VULNERABILITY] Can join even when banned

### ISSUE THREAD

**Issue by regalstreak** [SEEDTEAM/TeleSeed#175]
# Considering supergroups:

See, like you **just banned** a user from a group, he/she will be able to **add himself/herself back** by just sending **/join [group id] in pm** of the bot! Please fix this thing. Till then, I advise you guys to remove the join thing from inpm.lua Maybe ill submit a PR for a hack after testing it

**Comment by regalstreak** [comment]
Commits:
https://github.com/regalstreak/XManager/commit/1403c9a8b7b04eabcac2bb251880c286995789ef
https://github.com/regalstreak/XManager/commit/ad3792c7f4cc26a8171c4b79af66e514f24e186d
https://github.com/regalstreak/XManager/commit/aa395747d9a923c7ba45ef2671442c8f4e7d106b
https://github.com/regalstreak/XManager/commit/1933f48c1dc8acf1f1aebb848209385c773422da

(I removed it completely as i do not require it. You may just remove the important part)

**Comment by TiagoDanin** [comment]
Both TeleSeed [V4](https://github.com/SEEDTEAM/TeleSeed/blob/supergroups/plugins/inpm.lua#L159) and [V2](https://github.com/SEEDTEAM/TeleSeed/blob/master/plugins/inpm.lua#L44) has filter for user banned.

**Comment by regalstreak** [comment]
Idk but you may try once. The filter didn't work for me. I had added it as a public group, so the id was visible via !chatlist

Also i had made teleseed an admin :sigh:

But the bug is still there

**Comment by ghost** [comment]
Man regalstreak you really like to kill me right?
Btw you need to ban me in the bot, not by yourself
If you'd have banned me in the bot it wouldn't allow me to return

**Comment by regalstreak** [comment]
@anupritaisno1 you make 40 accounts and get in somehow. No use. Do whatever you want to.
