### ISSUE TITLE
Migrating to Official API

### ISSUE THREAD

**Issue by kamikazechaser** [SEEDTEAM/TeleSeed#177]
Telegram-CLI is now proving to be a burden. In the recent days, kick and ban by reply has stopped working. Telegram-CLI also doesnt seem to capacitate for large groups.
I therefore propose a migration to Official API.

Add Enhancement Label

**Comment by LucentW** [comment]
The issue about official APIs is that there are no alternatives to e.g. `resolve_username`, `chat_info` and `del_msg`.
Also you have no control over the administrators' list, no way to have the bot invite someone or join a group and so on.

It is feasible (I am infact _"writing"_ a library to wrap tg-cli based bots and get them to work over bot APIs), but would break quite a long list of features that can only be replaced by stubs.
