### ISSUE TITLE
lua

### ISSUE THREAD

**Issue by ghost** [SEEDTEAM/TeleSeed#191]
what is this? please help me

root@ubuntu:~/TeleSeed# ./launch.sh
rm: cannot remove '../.telegram-cli/state': No such file or directory
change_user_group: can't find the user telegramd to switch to
Telegram-cli version 1.4.1, Copyright (C) 2013-2015 Vitaly Valtman
Telegram-cli comes with ABSOLUTELY NO WARRANTY; for details type `show_license'.
This is free software, and you are welcome to redistribute it
under certain conditions; type`show_license' for details.
Telegram-cli uses libtgl version 2.1.0
Telegram-cli includes software developed by the OpenSSL Project
for use in the OpenSSL Toolkit. (http://www.openssl.org/)
I: config dir=[/root/.telegram-cli]
 **\* 1470509352.134142 lua: .///bot/utils.lua:3: module 'ssl.https' not found:
        no field package.preload['ssl.https']
        no file '/usr/local/share/lua/5.2/ssl/https.lua'
        no file '/usr/local/share/lua/5.2/ssl/https/init.lua'
        no file '/usr/local/lib/lua/5.2/ssl/https.lua'
        no file '/usr/local/lib/lua/5.2/ssl/https/init.lua'
        no file '/usr/share/lua/5.2/ssl/https.lua'
        no file '/usr/share/lua/5.2/ssl/https/init.lua'
        no file './ssl/https.lua'
        no file '.luarocks/share/lua/5.2/ssl/https.lua'
        no file '.luarocks/share/lua/5.2/ssl/https/init.lua'
        no file '/usr/local/lib/lua/5.2/ssl/https.so'
        no file '/usr/lib/x86_64-linux-gnu/lua/5.2/ssl/https.so'
        no file '/usr/lib/lua/5.2/ssl/https.so'
        no file '/usr/local/lib/lua/5.2/loadall.so'
        no file './ssl/https.so'
        no file '.luarocks/lib/lua/5.2/ssl/https.so'
        no file '/usr/local/lib/lua/5.2/ssl.so'
        no file '/usr/lib/x86_64-linux-gnu/lua/5.2/ssl.so'
        no file '/usr/lib/lua/5.2/ssl.so'
        no file '/usr/local/lib/lua/5.2/loadall.so'
        no file './ssl.so'
        no file '.luarocks/lib/lua/5.2/ssl.so'
root@ubuntu:~/TeleSeed#

**Comment by TiagoDanin** [comment]
Please check the manual. 
- [Installation TeleSeedV2](https://github.com/SEEDTEAM/TeleSeed#installation)
- [Installation TeleSeedV4](https://github.com/SEEDTEAM/TeleSeed/tree/supergroups#installation)
