### ISSUE TITLE
Problem With Replay

### ISSUE THREAD

**Issue by MrKiaN** [SEEDTEAM/TeleSeed#195]
I have Problem, Replay ID Doesn't Work

Log:

Support MaKeRMaN »»» [reply to ] !id
 **\* 1473067802.611901 id=481
 **\* 1473067802.611924 id=481
Old message :(
 **\* 1473067802.621172 lua: plugins/Supergroup.lua:654: attempt to index local 'result' (a boolean value)

**Comment by MrKiaN** [comment]
:-\

**Comment by buzz3rs** [comment]
[TeleSeed](https://github.com/SEEDTEAM/TeleSeedl) like all other cli bots doesnt support **old messages** in **supergroups**
The project is **closed** (no updates yet)
**So there is no solution for your problem right now**

**Comment by TiagoDanin** [comment]
Commit: [Fix TG-Link and old msg](https://github.com/SEEDTEAM/TeleSeed/commit/9d081384c4cb080ae8ef1c27d960189802267614) 1e7b80d

Open Terminal:
- 1. `./launch update`
- 2. `./launch`
