### ISSUE TITLE
not support multi big supergroup?

### ISSUE THREAD

**Issue by mammad2c** [SEEDTEAM/TeleSeed#199]
Hi,
one bot cannot support multi big supergroup(200 members up)?

**Comment by DatDraggy** [comment]
https://github.com/SEEDTEAM/TeleSeed/issues/197
Try this. I am doing it rn. Will tell you if it worked

EDIT: Nope doesn't work. Maybe somebody could help?

> [15:20:44]root@dragonhoard /home/pi/Desktop/TeleSeed $ ./launch.sh
> rm: Entfernen von „../.telegram-cli/state“ nicht möglich: File or directory not found
> change_user_group: can't find the user telegramd to switch to
> Telegram-cli version 1.4.1, Copyright (C) 2013-2015 Vitaly Valtman
> Telegram-cli comes with ABSOLUTELY NO WARRANTY; for details type `show_license'.
> This is free software, and you are welcome to redistribute it
> under certain conditions; type`show_license' for details.
> Telegram-cli uses libtgl version 2.1.0
> Telegram-cli includes software developed by the OpenSSL Project
> for use in the OpenSSL Toolkit. (http://www.openssl.org/)
> I: config dir=[/root/.telegram-cli]
>  **\* 1475504722.193439 lua: .///bot/utils.lua:1: module 'socket.url' not found:
>         no field package.preload['socket.url']
>         no file '/usr/local/share/lua/5.2/socket/url.lua'
>         no file '/usr/local/share/lua/5.2/socket/url/init.lua'
>         no file '/usr/local/lib/lua/5.2/socket/url.lua'
>         no file '/usr/local/lib/lua/5.2/socket/url/init.lua'
>         no file './socket/url.lua'
>         no file '/usr/share/lua/5.2/socket/url.lua'
>         no file '/usr/share/lua/5.2/socket/url/init.lua'
>         no file './socket/url.lua'
>         no file '.luarocks/share/lua/5.2/socket/url.lua'
>         no file '.luarocks/share/lua/5.2/socket/url/init.lua'
>         no file '/usr/local/lib/lua/5.2/socket/url.so'
>         no file '/usr/lib/arm-linux-gnueabihf/lua/5.2/socket/url.so'
>         no file '/usr/lib/lua/5.2/socket/url.so'
>         no file '/usr/local/lib/lua/5.2/loadall.so'
>         no file './socket/url.so'
>         no file '.luarocks/lib/lua/5.2/socket/url.so'
>         no file '/usr/local/lib/lua/5.2/socket.so'
>         no file '/usr/lib/arm-linux-gnueabihf/lua/5.2/socket.so'
>         no file '/usr/lib/lua/5.2/socket.so'
>         no file '/usr/local/lib/lua/5.2/loadall.so'
>         no file './socket.so'

**Comment by mammad2c** [comment]
@WInf9Kieran only work in one big super group, because one group has been focused in Telegram Dekstop. If i want to support multi big super groups, I have to run multiple Telegram Desktop :| . 
Is there any solution to just only focused in one group and support another?

**Comment by ticoti** [comment]
now even what @mammad2c  has stopped working :/

**Comment by Dragon-Born** [comment]
Wait for new version
