### ISSUE TITLE
Push the GIF bug fix

### ISSUE THREAD

**Issue by parsagachkardev** [SEEDTEAM/TeleSeed#63]
Please fork the telegram-cli and use your private tg-cli repo, and also push the assertion "0" fail fix to it. This fix seems to be working : https://github.com/vysheng/tg/issues/904
The Owners don't push the fix I don't know Why :tired_face:

**Comment by Imandaneshi** [comment]
Updated

**Comment by arabsoheyl** [comment]
mayby you should update some of param of this file(sceme.tl).

latest scheme:
https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/Resources/scheme.tl


and run this commands

make clean
./configure
make
