### ISSUE TITLE
block_user.lua

### ISSUE THREAD

**Issue by thisishmed** [SEEDTEAM/TeleSeed#67]
lua: plugins/block_user.lua:8: attempt to call global 'unblock_user' (a nil value)

please help

**Comment by Rondoozle** [comment]
This issue has been resolved in the current "Test" branch.

**Comment by hmon** [comment]
use fucking test branch

**Comment by RememberTheAir** [comment]
What the hell is this?

**Comment by Imandaneshi** [comment]
It should work now
