### ISSUE TITLE
Can't connect with Redis, install/configure it!

### ISSUE THREAD

**Issue by parsagachkardev** [SEEDTEAM/TeleSeed#68]
The bot keeps printing out this error in red & banhammer doesn't work.
`Can't connect with Redis, install/configure it!`
i think this guy is having the same issue https://github.com/SEEDTEAM/TeleSeed/issues/62
I've noticed this issue using C9.io on other VPS like Koding or PermiumVPS's banhammer was fine.

**Note:**
i've already installed Redis and configured it _(Do i need special Redis setup?)_

**Comment by Imandaneshi** [comment]
``` bash
sudo service redis-server start
```

U just need to start your redis server,that;s all
