### ISSUE TITLE
Not working with Supergroups

### ISSUE THREAD

**Issue by tman862** [SEEDTEAM/TeleSeed#71]
Bot isn't working with super groups. No output from the chats in the console, or response actions in the chat itself.

**Comment by ThisIsArman** [comment]
bullshit

**Comment by RememberTheAir** [comment]
Do you read somewhere that supergroups are supported?
There is a document called "README". It's called "README" cause you have to read it.

**Comment by RememberTheAir** [comment]
Wait what
