### ISSUE TITLE
Group Don't Make

### ISSUE THREAD

**Issue by delram** [SEEDTEAM/TeleSeed#72]
Hi,I have a big problem...

Why after making seven or eight groups, Creategroup/Createrealm command does not work?

**Comment by mrhalix** [comment]
becuse telegram limits

**Comment by delram** [comment]
How can I solve this problem?
can?

**Comment by Alhur1** [comment]
Contact telegram at +42400

**Comment by delram** [comment]
@Alhur1 
When respond?

**Comment by Imandaneshi** [comment]
This is not related to teleseed source
