### ISSUE TITLE
bot doesn't respond in new plugin & update

### ISSUE THREAD

**Issue by pekkahacker** [SEEDTEAM/TeleSeed#79]
bot doesn't respond in new plugin & update to me
it only respond when i send /id and it give my bot and my id
i try /help,!help etc......
thats my command my id is 131681931 and my bot id is 197095603
my username @zoomfastestman
my bot username @TeleZoom
oh and i used c9.io
..............................................................................................................................................................
Telegram-cli version 1.3.3, Copyright (C) 2013-2015 Vitaly Valtman
Telegram-cli comes with ABSOLUTELY NO WARRANTY; for details type `show_license'.
This is free software, and you are welcome to redistribute it
under certain conditions; type`show_license' for details.
Telegram-cli uses libtgl version 2.0.3
Telegram-cli includes software developed by the OpenSSL Project
for use in the OpenSSL Toolkit. (http://www.openssl.org/)
Telegram-cli uses libpython version 3.5.1
I: config dir=[/home/ubuntu/.telegram-cli]
Allowed user: 110626080
Allowed user: 197095603
Allowed user: 111020322
Allowed user: 111020322
Allowed user: 131681931
Allowed user: 197095603
Loading plugin  onservice
Loading plugin  inrealm
Loading plugin  ingroup
Loading plugin  inpm
Loading plugin  banhammer
Loading plugin  stats
Loading plugin  anti_spam
Loading plugin  owners
Loading plugin  arabic_lock
Loading plugin  set
Loading plugin  get
Loading plugin  broadcast
Loading plugin  download_media
Loading plugin  invite
Loading plugin  all
Loading plugin  leave_ban
Loading plugin  admin

**Comment by Imandaneshi** [comment]
It's working just fine
